package br.com.portfolio.domain.response;

import br.com.portfolio.domain.Customer;
import br.com.portfolio.domain.GenderEnum;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import lombok.RequiredArgsConstructor;
import org.bson.types.ObjectId;

@RequiredArgsConstructor
public class CustomerResponse {

    @JsonIgnore
    private final Customer customer;

    @ApiModelProperty("Customer autogenerated id")
    public ObjectId getId() {
        return customer.getId();
    }

    @ApiModelProperty("Customer's name")
    public String getName() {
        return customer.getName();
    }

    @ApiModelProperty("Customer's gender")
    public GenderEnum getGender() {
        return customer.getGender();
    }

    @ApiModelProperty("Customer's nickname")
    public String getNickname() {
        return customer.getNickname();
    }

    @ApiModelProperty("Customer's email")
    public String getEmail() {
        return customer.getEmail();
    }

    @ApiModelProperty("Customer's birthDate")
    public LocalDate getBirthDate() {
        return customer.getBirthDate();
    }

    @ApiModelProperty("Customer's document Number")
    public String getDocumentNumber() {
        return customer.getDocumentNumber();
    }
}
